name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn clean package install
        working-directory: /Exercicio-7/Semana10
        run: |
          sudo apt-get update
          sudo apt-get install java
          sudo apt-get install maven
          mvn clean package install
       

