name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: openjdk:latest
    steps:
      - name: Run a one-line script
        run: mvn clean package install

