name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn clean package install
        run: |
          cd /Exercicio-7/Semana10
          mvn clean package install
       

