name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test
        working-directory: Exercicio-7-8-9/Semana10
      - name: Maven package
        run: mvn package
        working-directory: Exercicio-7-8-9/Semana10
      - name: Generate docker image
        run: docker image build -t book-store:01.00.00 .
        working-directory: Exercicio-7-8-9/Semana10
      - name: Test frontend application.
        run: |
          yarn
          yarn test
        working-directory: Exercicio-10/bookstore


