name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn clean package install
        run: |
          echo Entrando no bash
          cd /Exercicio-7/Semana10
          echo Entrando na pasta do arquivo
          mvn clean package install
          echo Comando executado com sucesso
       

