name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn clean package install
        run: mvn clean package install
        working-directory: ./Exercicio-7/Semana10

